# SPDX-FileCopyrightText: 2022 Andrea Pappacoda <andrea@pappacoda.it>
#
# SPDX-License-Identifier: Apache-2.0

language: cpp

os: linux
dist: jammy
arch: [ amd64, arm64, ppc64le, s390x ]

branches:
  only: master

addons:
  apt:
    update: true
    packages:
    - meson
    - pkg-config
    - cmake
    - rapidjson-dev
    - libhowardhinnant-date-dev
    - libssl-dev
    - libgtest-dev
    - libcurl4-openssl-dev

script:
- meson setup build -DPISTACHE_BUILD_TESTS=true
- ninja -C build
- meson test -C build --verbose
